"""Initial migration

Revision ID: 9a4e9a02e8f9
Revises: 
Create Date: 2026-07-09 16:51:14.344486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4e9a02e8f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('occupancy', sa.Integer(), nullable=True),
    sa.Column('outdoor_temp', sa.Float(), nullable=True),
    sa.Column('outdoor_humidity', sa.Float(), nullable=True),
    sa.Column('recommended_setpoint', sa.Float(), nullable=True),
    sa.Column('recommended_mode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_logs_id'), 'optimization_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_logs_id'), table_name='optimization_logs')
    op.drop_table('optimization_logs')
    # ### end Alembic commands ###
